// <auto-generated>
//     This code was generated by a WinForms designer.
// </auto-generated>
#nullable disable

namespace pharmacy.Forms.Purchases
{
    public partial class FrmPurchaseList
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            dgv = new DataGridView();
            toolbar = new FlowLayoutPanel();
            btnRefresh = new Button();
            btnView = new Button();
            SuspendLayout();
            // 
            // dgv
            // 
            dgv.Dock = DockStyle.Fill;
            dgv.Name = "dgv";
            dgv.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_CellDoubleClick);
            // 
            // btnRefresh
            // 
            btnRefresh.BackColor = Color.FromArgb(41, 128, 185);
            btnRefresh.Cursor = Cursors.Hand;
            btnRefresh.FlatAppearance.BorderSize = 0;
            btnRefresh.FlatStyle = FlatStyle.Flat;
            btnRefresh.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnRefresh.ForeColor = Color.White;
            btnRefresh.Margin = new Padding(0, 2, 8, 0);
            btnRefresh.Name = "btnRefresh";
            btnRefresh.Size = new Size(110, 36);
            btnRefresh.Text = "Refresh";
            btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            // 
            // btnView
            // 
            btnView.BackColor = Color.FromArgb(39, 174, 96);
            btnView.Cursor = Cursors.Hand;
            btnView.FlatAppearance.BorderSize = 0;
            btnView.FlatStyle = FlatStyle.Flat;
            btnView.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnView.ForeColor = Color.White;
            btnView.Margin = new Padding(0, 2, 8, 0);
            btnView.Name = "btnView";
            btnView.Size = new Size(110, 36);
            btnView.Text = "View";
            btnView.Click += new System.EventHandler(this.btnView_Click);
            // 
            // toolbar
            // 
            toolbar.Controls.Add(btnRefresh);
            toolbar.Controls.Add(btnView);
            toolbar.Dock = DockStyle.Top;
            toolbar.Height = 48;
            toolbar.Name = "toolbar";
            toolbar.Padding = new Padding(8, 8, 8, 0);
            toolbar.WrapContents = false;
            // 
            // FrmPurchaseList
            // 
            ClientSize = new Size(900, 480);
            Controls.Add(dgv);
            Controls.Add(toolbar);
            MinimumSize = new Size(600, 350);
            Name = "FrmPurchaseList";
            Text = "Purchases";
            Load += new System.EventHandler(this.FrmPurchaseList_Load);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.FlowLayoutPanel toolbar;
        private System.Windows.Forms.Button btnRefresh;
        private System.Windows.Forms.Button btnView;
    }

    public partial class FrmPurchaseView
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            root = new TableLayoutPanel();
            info = new Label();
            dgv = new DataGridView();
            btnPanel = new FlowLayoutPanel();
            btnClose = new Button();
            SuspendLayout();
            // 
            // root
            // 
            root.ColumnCount = 1;
            root.Dock = DockStyle.Fill;
            root.Name = "root";
            root.Padding = new Padding(12);
            root.RowCount = 3;
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 90));
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 52));
            root.Controls.Add(info, 0, 0);
            root.Controls.Add(dgv, 0, 1);
            root.Controls.Add(btnPanel, 0, 2);
            // 
            // info
            // 
            info.Dock = DockStyle.Fill;
            info.Name = "info";
            // 
            // dgv
            // 
            dgv.Dock = DockStyle.Fill;
            dgv.Name = "dgv";
            // 
            // btnClose
            // 
            btnClose.BackColor = Color.FromArgb(149, 165, 166);
            btnClose.Cursor = Cursors.Hand;
            btnClose.FlatAppearance.BorderSize = 0;
            btnClose.FlatStyle = FlatStyle.Flat;
            btnClose.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnClose.ForeColor = Color.White;
            btnClose.Name = "btnClose";
            btnClose.Size = new Size(110, 36);
            btnClose.Text = "Close";
            btnClose.Click += new System.EventHandler(this.btnClose_Click);
            // 
            // btnPanel
            // 
            btnPanel.Controls.Add(btnClose);
            btnPanel.Dock = DockStyle.Fill;
            btnPanel.FlowDirection = FlowDirection.RightToLeft;
            btnPanel.Name = "btnPanel";
            // 
            // FrmPurchaseView
            // 
            AcceptButton = btnClose;
            ClientSize = new Size(700, 440);
            Controls.Add(root);
            MinimumSize = new Size(500, 350);
            Name = "FrmPurchaseView";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel root;
        private System.Windows.Forms.Label info;
        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.FlowLayoutPanel btnPanel;
        private System.Windows.Forms.Button btnClose;
    }

    public partial class FrmPurchaseNew
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            cmbSupplier = new ComboBox();
            cmbProduct = new ComboBox();
            txtBatch = new TextBox();
            dtExpiry = new DateTimePicker();
            numQty = new NumericUpDown();
            numCost = new NumericUpDown();
            dgv = new DataGridView();
            lblTotal = new Label();
            btnNewSupplier = new Button();
            btnNewProduct = new Button();
            btnAddLine = new Button();
            btnRemoveLine = new Button();
            btnSave = new Button();
            split = new TableLayoutPanel();
            form = new TableLayoutPanel();
            qtyCost = new FlowLayoutPanel();
            lineButtons = new FlowLayoutPanel();
            right = new TableLayoutPanel();
            bottom = new FlowLayoutPanel();
            SuspendLayout();
            // 
            // cmbSupplier
            // 
            cmbSupplier.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbSupplier.Name = "cmbSupplier";
            // 
            // cmbProduct
            // 
            cmbProduct.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbProduct.Name = "cmbProduct";
            cmbProduct.SelectedIndexChanged += new System.EventHandler(this.cmbProduct_SelectedIndexChanged);
            // 
            // txtBatch
            // 
            txtBatch.Name = "txtBatch";
            // 
            // dtExpiry
            // 
            dtExpiry.Format = DateTimePickerFormat.Short;
            dtExpiry.Name = "dtExpiry";
            dtExpiry.Value = DateTime.Today.AddYears(1);
            // 
            // numQty
            // 
            numQty.Maximum = 99999;
            numQty.Minimum = 1;
            numQty.Name = "numQty";
            numQty.Value = 1;
            numQty.Width = 70;
            // 
            // numCost
            // 
            numCost.DecimalPlaces = 2;
            numCost.Increment = 0.25m;
            numCost.Maximum = 1000000;
            numCost.Name = "numCost";
            numCost.Width = 110;
            // 
            // dgv
            // 
            dgv.Dock = DockStyle.Fill;
            dgv.Name = "dgv";
            // 
            // lblTotal
            // 
            lblTotal.Dock = DockStyle.Fill;
            lblTotal.Font = new Font("Segoe UI", 14F, FontStyle.Bold);
            lblTotal.ForeColor = Color.FromArgb(41, 128, 185);
            lblTotal.Name = "lblTotal";
            lblTotal.TextAlign = ContentAlignment.MiddleLeft;
            // 
            // btnNewSupplier
            // 
            btnNewSupplier.BackColor = Color.FromArgb(41, 128, 185);
            btnNewSupplier.Cursor = Cursors.Hand;
            btnNewSupplier.Dock = DockStyle.Fill;
            btnNewSupplier.FlatAppearance.BorderSize = 0;
            btnNewSupplier.FlatStyle = FlatStyle.Flat;
            btnNewSupplier.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnNewSupplier.ForeColor = Color.White;
            btnNewSupplier.Name = "btnNewSupplier";
            btnNewSupplier.Size = new Size(110, 36);
            btnNewSupplier.Text = "+ New";
            btnNewSupplier.Click += new System.EventHandler(this.btnNewSupplier_Click);
            // 
            // btnNewProduct
            // 
            btnNewProduct.BackColor = Color.FromArgb(41, 128, 185);
            btnNewProduct.Cursor = Cursors.Hand;
            btnNewProduct.Dock = DockStyle.Fill;
            btnNewProduct.FlatAppearance.BorderSize = 0;
            btnNewProduct.FlatStyle = FlatStyle.Flat;
            btnNewProduct.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnNewProduct.ForeColor = Color.White;
            btnNewProduct.Name = "btnNewProduct";
            btnNewProduct.Size = new Size(110, 36);
            btnNewProduct.Text = "+ New";
            btnNewProduct.Click += new System.EventHandler(this.btnNewProduct_Click);
            // 
            // btnAddLine
            // 
            btnAddLine.BackColor = Color.FromArgb(41, 128, 185);
            btnAddLine.Cursor = Cursors.Hand;
            btnAddLine.FlatAppearance.BorderSize = 0;
            btnAddLine.FlatStyle = FlatStyle.Flat;
            btnAddLine.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnAddLine.ForeColor = Color.White;
            btnAddLine.Margin = new Padding(0, 0, 8, 0);
            btnAddLine.Name = "btnAddLine";
            btnAddLine.Size = new Size(110, 36);
            btnAddLine.Text = "Add Line";
            btnAddLine.Click += new System.EventHandler(this.btnAddLine_Click);
            // 
            // btnRemoveLine
            // 
            btnRemoveLine.BackColor = Color.FromArgb(192, 57, 43);
            btnRemoveLine.Cursor = Cursors.Hand;
            btnRemoveLine.FlatAppearance.BorderSize = 0;
            btnRemoveLine.FlatStyle = FlatStyle.Flat;
            btnRemoveLine.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnRemoveLine.ForeColor = Color.White;
            btnRemoveLine.Name = "btnRemoveLine";
            btnRemoveLine.Size = new Size(110, 36);
            btnRemoveLine.Text = "Remove Line";
            btnRemoveLine.Click += new System.EventHandler(this.btnRemoveLine_Click);
            // 
            // btnSave
            // 
            btnSave.BackColor = Color.FromArgb(39, 174, 96);
            btnSave.Cursor = Cursors.Hand;
            btnSave.FlatAppearance.BorderSize = 0;
            btnSave.FlatStyle = FlatStyle.Flat;
            btnSave.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnSave.ForeColor = Color.White;
            btnSave.Name = "btnSave";
            btnSave.Size = new Size(110, 36);
            btnSave.Text = "Save Purchase";
            btnSave.Size = new Size(180, 44);
            btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // qtyCost
            // 
            qtyCost.Controls.Add(numQty);
            qtyCost.Controls.Add(numCost);
            qtyCost.Dock = DockStyle.Fill;
            qtyCost.Name = "qtyCost";
            qtyCost.Padding = new Padding(0, 4, 0, 0);
            // 
            // lineButtons
            // 
            lineButtons.Controls.Add(btnAddLine);
            lineButtons.Controls.Add(btnRemoveLine);
            lineButtons.Dock = DockStyle.Fill;
            lineButtons.Name = "lineButtons";
            lineButtons.Padding = new Padding(0, 6, 0, 0);
            // 
            // split
            // 
            split.ColumnCount = 2;
            split.Dock = DockStyle.Fill;
            split.Name = "split";
            split.Padding = new Padding(8);
            split.RowCount = 1;
            split.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 420));
            split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            split.Controls.Add(form, 0, 0);
            split.Controls.Add(right, 1, 0);
            // 
            // form
            // 
            form.ColumnCount = 3;
            form.Dock = DockStyle.Fill;
            form.Name = "form";
            form.Padding = new Padding(0, 0, 12, 0);
            form.RowCount = 6;
            form.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90));
            form.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            form.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 70));
            form.RowStyles.Add(new RowStyle(SizeType.Absolute, 36));
            form.RowStyles.Add(new RowStyle(SizeType.Absolute, 36));
            form.RowStyles.Add(new RowStyle(SizeType.Absolute, 36));
            form.RowStyles.Add(new RowStyle(SizeType.Absolute, 36));
            form.RowStyles.Add(new RowStyle(SizeType.Absolute, 36));
            form.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            form.Controls.Add(lineButtons, 1, 5);
            // 
            // right
            // 
            right.ColumnCount = 1;
            right.Dock = DockStyle.Fill;
            right.Name = "right";
            right.RowCount = 2;
            right.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            right.RowStyles.Add(new RowStyle(SizeType.Absolute, 48));
            right.Controls.Add(dgv, 0, 0);
            right.Controls.Add(lblTotal, 0, 1);
            // 
            // bottom
            // 
            bottom.Controls.Add(btnSave);
            bottom.Dock = DockStyle.Bottom;
            bottom.FlowDirection = FlowDirection.RightToLeft;
            bottom.Height = 56;
            bottom.Name = "bottom";
            bottom.Padding = new Padding(8);
            // 
            // FrmPurchaseNew
            // 
            ClientSize = new Size(1000, 560);
            Controls.Add(split);
            Controls.Add(bottom);
            MinimumSize = new Size(750, 450);
            Name = "FrmPurchaseNew";
            Text = "New Purchase";
            Load += new System.EventHandler(this.FrmPurchaseNew_Load);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.ComboBox cmbSupplier;
        private System.Windows.Forms.ComboBox cmbProduct;
        private System.Windows.Forms.TextBox txtBatch;
        private System.Windows.Forms.DateTimePicker dtExpiry;
        private System.Windows.Forms.NumericUpDown numQty;
        private System.Windows.Forms.NumericUpDown numCost;
        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.Label lblTotal;
        private System.Windows.Forms.Button btnNewSupplier;
        private System.Windows.Forms.Button btnNewProduct;
        private System.Windows.Forms.Button btnAddLine;
        private System.Windows.Forms.Button btnRemoveLine;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.TableLayoutPanel split;
        private System.Windows.Forms.TableLayoutPanel form;
        private System.Windows.Forms.FlowLayoutPanel qtyCost;
        private System.Windows.Forms.FlowLayoutPanel lineButtons;
        private System.Windows.Forms.TableLayoutPanel right;
        private System.Windows.Forms.FlowLayoutPanel bottom;
    }
}
