// <auto-generated>
//     This code was generated by a WinForms designer.
// </auto-generated>
#nullable disable

namespace pharmacy.Forms.Users
{
    public partial class FrmUserList
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            toolbar = new FlowLayoutPanel();
            btnNew = new Button();
            btnEdit = new Button();
            btnDeactivate = new Button();
            btnRemove = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            toolbar.Controls.AddRange(new Control[] { btnNew, btnEdit, btnDeactivate, btnRemove });
            toolbar.Dock = DockStyle.Top;
            toolbar.Height = 48;
            toolbar.Padding = new Padding(8, 8, 8, 0);
            toolbar.WrapContents = false;
            btnNew.BackColor = Color.FromArgb(41, 128, 185);
            btnNew.Cursor = Cursors.Hand;
            btnNew.FlatAppearance.BorderSize = 0;
            btnNew.FlatStyle = FlatStyle.Flat;
            btnNew.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnNew.ForeColor = Color.White;
            btnNew.Height = 36;
            btnNew.Width = 110;
            btnNew.Margin = new Padding(0, 2, 8, 0);
            btnNew.Text = "New (F2)";
            btnNew.Click += new System.EventHandler(this.btnNew_Click);
            btnEdit.BackColor = Color.FromArgb(39, 174, 96);
            btnEdit.Cursor = Cursors.Hand;
            btnEdit.FlatAppearance.BorderSize = 0;
            btnEdit.FlatStyle = FlatStyle.Flat;
            btnEdit.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnEdit.ForeColor = Color.White;
            btnEdit.Height = 36;
            btnEdit.Width = 110;
            btnEdit.Margin = new Padding(0, 2, 8, 0);
            btnEdit.Text = "Edit";
            btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            btnDeactivate.BackColor = Color.FromArgb(231, 76, 60);
            btnDeactivate.Cursor = Cursors.Hand;
            btnDeactivate.FlatAppearance.BorderSize = 0;
            btnDeactivate.FlatStyle = FlatStyle.Flat;
            btnDeactivate.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnDeactivate.ForeColor = Color.White;
            btnDeactivate.Height = 36;
            btnDeactivate.Width = 120;
            btnDeactivate.Margin = new Padding(0, 2, 8, 0);
            btnDeactivate.Text = "Deactivate";
            btnDeactivate.Click += new System.EventHandler(this.btnDeactivate_Click);
            btnRemove.BackColor = Color.FromArgb(192, 57, 43);
            btnRemove.Cursor = Cursors.Hand;
            btnRemove.FlatAppearance.BorderSize = 0;
            btnRemove.FlatStyle = FlatStyle.Flat;
            btnRemove.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnRemove.ForeColor = Color.White;
            btnRemove.Height = 36;
            btnRemove.Width = 140;
            btnRemove.Margin = new Padding(0, 2, 8, 0);
            btnRemove.Text = "Remove Account";
            btnRemove.Click += new System.EventHandler(this.btnRemove_Click);
            dgv.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_CellDoubleClick);
            dgv.Dock = DockStyle.Fill;
            ClientSize = new Size(780, 450);
            Controls.AddRange(new Control[] { dgv, toolbar });
            KeyDown += new System.Windows.Forms.KeyEventHandler(this.FrmUserList_KeyDown);
            Load += new System.EventHandler(this.FrmUserList_Load);
            MinimumSize = new Size(550, 320);
            Text = "Users";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel toolbar;
        private System.Windows.Forms.Button btnNew;
        private System.Windows.Forms.Button btnEdit;
        private System.Windows.Forms.Button btnDeactivate;
        private System.Windows.Forms.Button btnRemove;
        private System.Windows.Forms.DataGridView dgv;
    }

    public partial class FrmUserEdit
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            layout = new TableLayoutPanel();
            lblUsername = new Label();
            txtUsername = new TextBox();
            lblFullName = new Label();
            txtFullName = new TextBox();
            lblPassword = new Label();
            txtPassword = new TextBox();
            lblRole = new Label();
            cmbRole = new ComboBox();
            chkActive = new CheckBox();
            btnPanel = new FlowLayoutPanel();
            btnCancel = new Button();
            btnSave = new Button();
            root = new TableLayoutPanel();
            SuspendLayout();
            layout.Dock = DockStyle.Fill;
            layout.Padding = new Padding(16);
            layout.ColumnCount = 1;
            layout.RowCount = 9;
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 52));
            lblUsername.Anchor = AnchorStyles.Left;
            lblUsername.AutoSize = true;
            lblUsername.Text = "Username";
            layout.Controls.Add(lblUsername, 0, 0);
            txtUsername.Dock = DockStyle.Fill;
            layout.Controls.Add(txtUsername, 0, 1);
            lblFullName.Anchor = AnchorStyles.Left;
            lblFullName.AutoSize = true;
            lblFullName.Text = "Full Name";
            layout.Controls.Add(lblFullName, 0, 2);
            txtFullName.Dock = DockStyle.Fill;
            layout.Controls.Add(txtFullName, 0, 3);
            lblPassword.Anchor = AnchorStyles.Left;
            lblPassword.AutoSize = true;
            lblPassword.Text = "Password (blank keeps current)";
            layout.Controls.Add(lblPassword, 0, 4);
            txtPassword.Dock = DockStyle.Fill;
            txtPassword.UseSystemPasswordChar = true;
            layout.Controls.Add(txtPassword, 0, 5);
            lblRole.Anchor = AnchorStyles.Left;
            lblRole.AutoSize = true;
            lblRole.Text = "Role";
            layout.Controls.Add(lblRole, 0, 6);
            cmbRole.Dock = DockStyle.Fill;
            cmbRole.DropDownStyle = ComboBoxStyle.DropDownList;
            layout.Controls.Add(cmbRole, 0, 7);
            chkActive.Text = "Active (can log in)";
            layout.Controls.Add(chkActive, 0, 8);
            btnCancel.BackColor = Color.FromArgb(149, 165, 166);
            btnCancel.Cursor = Cursors.Hand;
            btnCancel.FlatAppearance.BorderSize = 0;
            btnCancel.FlatStyle = FlatStyle.Flat;
            btnCancel.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnCancel.ForeColor = Color.White;
            btnCancel.Height = 36;
            btnCancel.Width = 110;
            btnCancel.Text = "Cancel";
            btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            btnSave.BackColor = Color.FromArgb(39, 174, 96);
            btnSave.Cursor = Cursors.Hand;
            btnSave.FlatAppearance.BorderSize = 0;
            btnSave.FlatStyle = FlatStyle.Flat;
            btnSave.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnSave.ForeColor = Color.White;
            btnSave.Height = 36;
            btnSave.Width = 110;
            btnSave.Text = "Save";
            btnSave.Click += new System.EventHandler(this.btnSave_Click);
            btnPanel.Controls.Add(btnCancel);
            btnPanel.Controls.Add(btnSave);
            btnPanel.Dock = DockStyle.Fill;
            btnPanel.FlowDirection = FlowDirection.RightToLeft;
            btnPanel.Padding = new Padding(0, 8, 0, 0);
            root.Dock = DockStyle.Fill;
            root.RowCount = 2;
            root.ColumnCount = 1;
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 52));
            root.Controls.Add(layout, 0, 0);
            root.Controls.Add(btnPanel, 0, 1);
            AcceptButton = btnSave;
            CancelButton = btnCancel;
            ClientSize = new Size(440, 400);
            Controls.Add(root);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Shown += new System.EventHandler(this.FrmUserEdit_Shown);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel layout;
        private System.Windows.Forms.Label lblUsername;
        private System.Windows.Forms.TextBox txtUsername;
        private System.Windows.Forms.Label lblFullName;
        private System.Windows.Forms.TextBox txtFullName;
        private System.Windows.Forms.Label lblPassword;
        private System.Windows.Forms.TextBox txtPassword;
        private System.Windows.Forms.Label lblRole;
        private System.Windows.Forms.ComboBox cmbRole;
        private System.Windows.Forms.CheckBox chkActive;
        private System.Windows.Forms.FlowLayoutPanel btnPanel;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.TableLayoutPanel root;
    }
}
