// <auto-generated>
//     This code was generated by a WinForms designer.
// </auto-generated>
#nullable disable

namespace pharmacy.Forms
{
    public partial class FrmMain
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            pnlContent = new Panel();
            menu = new MenuStrip();
            status = new StatusStrip();
            lblUser = new ToolStripStatusLabel();
            ucDashboard = new pharmacy.UserControls.UcDashboardCard();
            dgvRecent = new DataGridView();
            lblRecentHeader = new Label();
            SuspendLayout();
            // 
            // pnlContent
            // 
            pnlContent.BackColor = Color.FromArgb(236, 240, 241);
            pnlContent.Dock = DockStyle.Fill;
            pnlContent.Padding = new Padding(10);
            // 
            // status
            // 
            status.Dock = DockStyle.Bottom;
            status.Items.Add(lblUser);
            // 
            // ucDashboard
            // 
            ucDashboard.CardOpened += new Action<int>(this.OpenDashboardCard);
            // 
            // FrmMain
            // 
            IsMdiContainer = true;
            WindowState = FormWindowState.Maximized;
            Controls.Add(pnlContent);
            Controls.Add(status);
            Controls.Add(menu);
            KeyDown += new System.Windows.Forms.KeyEventHandler(this.FrmMain_KeyDown);
            MainMenuStrip = menu;
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Panel pnlContent;
        private System.Windows.Forms.MenuStrip menu;
        private System.Windows.Forms.StatusStrip status;
        private System.Windows.Forms.ToolStripStatusLabel lblUser;
        private pharmacy.UserControls.UcDashboardCard ucDashboard;
        private System.Windows.Forms.DataGridView dgvRecent;
        private System.Windows.Forms.Label lblRecentHeader;
    }
}
