// <auto-generated>
//     This code was generated by a WinForms designer.
// </auto-generated>
#nullable disable

namespace pharmacy.Forms.Products
{
    public partial class FrmProductList
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            toolbar = new FlowLayoutPanel();
            lbl = new Label();
            txtSearch = new TextBox();
            btnNew = new Button();
            btnEdit = new Button();
            btnDelete = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            // 
            // toolbar
            // 
            toolbar.Controls.AddRange(new Control[] { lbl, txtSearch, btnNew, btnEdit, btnDelete });
            toolbar.Dock = DockStyle.Top;
            toolbar.Height = 48;
            toolbar.Padding = new Padding(8, 8, 8, 0);
            toolbar.WrapContents = false;
            // 
            // lbl
            // 
            lbl.AutoSize = true;
            lbl.Margin = new Padding(0, 10, 4, 0);
            lbl.Text = "Search:";
            // 
            // txtSearch
            // 
            txtSearch.Margin = new Padding(0, 6, 12, 0);
            txtSearch.Width = 280;
            txtSearch.TextChanged += new System.EventHandler(this.txtSearch_TextChanged);
            // 
            // btnNew
            // 
            btnNew.BackColor = Color.FromArgb(41, 128, 185);
            btnNew.Cursor = Cursors.Hand;
            btnNew.FlatAppearance.BorderSize = 0;
            btnNew.FlatStyle = FlatStyle.Flat;
            btnNew.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnNew.ForeColor = Color.White;
            btnNew.Height = 36;
            btnNew.Width = 110;
            btnNew.Margin = new Padding(0, 2, 8, 0);
            btnNew.Text = "New (F2)";
            btnNew.Click += new System.EventHandler(this.btnNew_Click);
            // 
            // btnEdit
            // 
            btnEdit.BackColor = Color.FromArgb(39, 174, 96);
            btnEdit.Cursor = Cursors.Hand;
            btnEdit.FlatAppearance.BorderSize = 0;
            btnEdit.FlatStyle = FlatStyle.Flat;
            btnEdit.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnEdit.ForeColor = Color.White;
            btnEdit.Height = 36;
            btnEdit.Width = 110;
            btnEdit.Margin = new Padding(0, 2, 8, 0);
            btnEdit.Text = "Edit";
            btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            // 
            // btnDelete
            // 
            btnDelete.BackColor = Color.FromArgb(231, 76, 60);
            btnDelete.Cursor = Cursors.Hand;
            btnDelete.FlatAppearance.BorderSize = 0;
            btnDelete.FlatStyle = FlatStyle.Flat;
            btnDelete.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnDelete.ForeColor = Color.White;
            btnDelete.Height = 36;
            btnDelete.Width = 110;
            btnDelete.Margin = new Padding(0, 2, 8, 0);
            btnDelete.Text = "Delete";
            btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // dgv
            // 
            dgv.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_CellDoubleClick);
            dgv.Dock = DockStyle.Fill;
            // 
            // FrmProductList
            // 
            ClientSize = new Size(950, 500);
            Controls.AddRange(new Control[] { dgv, toolbar });
            KeyDown += new System.Windows.Forms.KeyEventHandler(this.FrmProductList_KeyDown);
            Load += new System.EventHandler(this.FrmProductList_Load);
            MinimumSize = new Size(600, 350);
            Text = "Products";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel toolbar;
        private System.Windows.Forms.Label lbl;
        private System.Windows.Forms.TextBox txtSearch;
        private System.Windows.Forms.Button btnNew;
        private System.Windows.Forms.Button btnEdit;
        private System.Windows.Forms.Button btnDelete;
        private System.Windows.Forms.DataGridView dgv;
    }

    public partial class FrmProductEdit
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            layout = new TableLayoutPanel();
            txtName = new TextBox();
            txtBarcode = new TextBox();
            numUnit = new NumericUpDown();
            numCost = new NumericUpDown();
            numReorder = new NumericUpDown();
            chkRx = new CheckBox();
            cmbCategory = new ComboBox();
            btnPanel = new FlowLayoutPanel();
            btnCancel = new Button();
            btnSave = new Button();
            root = new TableLayoutPanel();
            SuspendLayout();
            // 
            // layout
            // 
            layout.Dock = DockStyle.Fill;
            layout.Padding = new Padding(16);
            layout.ColumnCount = 1;
            layout.RowCount = 13;
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 52));
            layout.Controls.Add(new Label { Text = "Category", AutoSize = true, Anchor = AnchorStyles.Left }, 0, 0);
            cmbCategory.Dock = DockStyle.Fill;
            cmbCategory.DropDownStyle = ComboBoxStyle.DropDownList;
            layout.Controls.Add(cmbCategory, 0, 1);
            layout.Controls.Add(new Label { Text = "Name", AutoSize = true, Anchor = AnchorStyles.Left }, 0, 2);
            txtName.Dock = DockStyle.Fill;
            layout.Controls.Add(txtName, 0, 3);
            layout.Controls.Add(new Label { Text = "Barcode", AutoSize = true, Anchor = AnchorStyles.Left }, 0, 4);
            txtBarcode.Dock = DockStyle.Fill;
            layout.Controls.Add(txtBarcode, 0, 5);
            layout.Controls.Add(new Label { Text = "Unit Price", AutoSize = true, Anchor = AnchorStyles.Left }, 0, 6);
            numUnit.Dock = DockStyle.Fill;
            numUnit.DecimalPlaces = 2;
            numUnit.Increment = 0.25m;
            numUnit.Maximum = 1000000;
            layout.Controls.Add(numUnit, 0, 7);
            layout.Controls.Add(new Label { Text = "Cost Price", AutoSize = true, Anchor = AnchorStyles.Left }, 0, 8);
            numCost.Dock = DockStyle.Fill;
            numCost.DecimalPlaces = 2;
            numCost.Increment = 0.25m;
            numCost.Maximum = 1000000;
            layout.Controls.Add(numCost, 0, 9);
            layout.Controls.Add(new Label { Text = "Reorder Level", AutoSize = true, Anchor = AnchorStyles.Left }, 0, 10);
            numReorder.Dock = DockStyle.Fill;
            numReorder.Maximum = 100000;
            layout.Controls.Add(numReorder, 0, 11);
            chkRx.Text = "Prescription required";
            layout.Controls.Add(chkRx, 0, 12);
            // 
            // btnCancel
            // 
            btnCancel.BackColor = Color.FromArgb(149, 165, 166);
            btnCancel.Cursor = Cursors.Hand;
            btnCancel.FlatAppearance.BorderSize = 0;
            btnCancel.FlatStyle = FlatStyle.Flat;
            btnCancel.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnCancel.ForeColor = Color.White;
            btnCancel.Height = 36;
            btnCancel.Width = 110;
            btnCancel.Text = "Cancel";
            btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnSave
            // 
            btnSave.BackColor = Color.FromArgb(39, 174, 96);
            btnSave.Cursor = Cursors.Hand;
            btnSave.FlatAppearance.BorderSize = 0;
            btnSave.FlatStyle = FlatStyle.Flat;
            btnSave.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnSave.ForeColor = Color.White;
            btnSave.Height = 36;
            btnSave.Width = 110;
            btnSave.Text = "Save";
            btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // btnPanel
            // 
            btnPanel.Controls.Add(btnCancel);
            btnPanel.Controls.Add(btnSave);
            btnPanel.Dock = DockStyle.Fill;
            btnPanel.FlowDirection = FlowDirection.RightToLeft;
            btnPanel.Padding = new Padding(0, 8, 0, 0);
            // 
            // root
            // 
            root.ColumnCount = 1;
            root.RowCount = 2;
            root.Dock = DockStyle.Fill;
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 52));
            root.Controls.Add(layout, 0, 0);
            root.Controls.Add(btnPanel, 0, 1);
            // 
            // FrmProductEdit
            // 
            AcceptButton = btnSave;
            CancelButton = btnCancel;
            ClientSize = new Size(480, 460);
            Controls.Add(root);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Shown += new System.EventHandler(this.FrmProductEdit_Shown);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel layout;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.TextBox txtBarcode;
        private System.Windows.Forms.NumericUpDown numUnit;
        private System.Windows.Forms.NumericUpDown numCost;
        private System.Windows.Forms.NumericUpDown numReorder;
        private System.Windows.Forms.CheckBox chkRx;
        private System.Windows.Forms.ComboBox cmbCategory;
        private System.Windows.Forms.FlowLayoutPanel btnPanel;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.TableLayoutPanel root;
    }
}
