// <auto-generated>
//     This code was generated by a WinForms designer.
// </auto-generated>
#nullable disable

namespace pharmacy.Forms.Suppliers
{
    public partial class FrmSupplierList
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            dgv = new DataGridView();
            txtSearch = new TextBox();
            toolbar = new FlowLayoutPanel();
            lbl = new Label();
            btnNew = new Button();
            btnEdit = new Button();
            btnDelete = new Button();
            SuspendLayout();
            // 
            // dgv
            // 
            dgv.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_CellDoubleClick);
            dgv.Dock = DockStyle.Fill;
            // 
            // txtSearch
            // 
            txtSearch.Margin = new Padding(0, 6, 12, 0);
            txtSearch.Width = 220;
            txtSearch.TextChanged += new System.EventHandler(this.txtSearch_TextChanged);
            // 
            // lbl
            // 
            lbl.AutoSize = true;
            lbl.Margin = new Padding(0, 10, 4, 0);
            lbl.Text = "Search:";
            // 
            // btnNew
            // 
            btnNew.BackColor = Color.FromArgb(41, 128, 185);
            btnNew.Cursor = Cursors.Hand;
            btnNew.FlatAppearance.BorderSize = 0;
            btnNew.FlatStyle = FlatStyle.Flat;
            btnNew.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnNew.ForeColor = Color.White;
            btnNew.Margin = new Padding(0, 2, 8, 0);
            btnNew.Size = new Size(110, 36);
            btnNew.Text = "New (F2)";
            btnNew.Click += new System.EventHandler(this.btnNew_Click);
            // 
            // btnEdit
            // 
            btnEdit.BackColor = Color.FromArgb(39, 174, 96);
            btnEdit.Cursor = Cursors.Hand;
            btnEdit.FlatAppearance.BorderSize = 0;
            btnEdit.FlatStyle = FlatStyle.Flat;
            btnEdit.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnEdit.ForeColor = Color.White;
            btnEdit.Margin = new Padding(0, 2, 8, 0);
            btnEdit.Size = new Size(110, 36);
            btnEdit.Text = "Edit";
            btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            // 
            // btnDelete
            // 
            btnDelete.BackColor = Color.FromArgb(231, 76, 60);
            btnDelete.Cursor = Cursors.Hand;
            btnDelete.FlatAppearance.BorderSize = 0;
            btnDelete.FlatStyle = FlatStyle.Flat;
            btnDelete.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnDelete.ForeColor = Color.White;
            btnDelete.Margin = new Padding(0, 2, 8, 0);
            btnDelete.Size = new Size(110, 36);
            btnDelete.Text = "Delete";
            btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // toolbar
            // 
            toolbar.Controls.Add(lbl);
            toolbar.Controls.Add(txtSearch);
            toolbar.Controls.Add(btnNew);
            toolbar.Controls.Add(btnEdit);
            toolbar.Controls.Add(btnDelete);
            toolbar.Dock = DockStyle.Top;
            toolbar.Height = 48;
            toolbar.Padding = new Padding(8, 8, 8, 0);
            toolbar.WrapContents = false;
            // 
            // FrmSupplierList
            // 
            ClientSize = new Size(800, 450);
            Controls.Add(dgv);
            Controls.Add(toolbar);
            KeyDown += new System.Windows.Forms.KeyEventHandler(this.FrmSupplierList_KeyDown);
            Load += new System.EventHandler(this.FrmSupplierList_Load);
            MinimumSize = new Size(550, 320);
            Text = "Suppliers";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.TextBox txtSearch;
        private System.Windows.Forms.FlowLayoutPanel toolbar;
        private System.Windows.Forms.Label lbl;
        private System.Windows.Forms.Button btnNew;
        private System.Windows.Forms.Button btnEdit;
        private System.Windows.Forms.Button btnDelete;
    }

    public partial class FrmSupplierEdit
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            txtName = new TextBox();
            txtPhone = new TextBox();
            txtEmail = new TextBox();
            txtAddress = new TextBox();
            chkActive = new CheckBox();
            lblName = new Label();
            lblPhone = new Label();
            lblEmail = new Label();
            lblAddress = new Label();
            tblLayout = new TableLayoutPanel();
            btnCancel = new Button();
            btnSave = new Button();
            btnPanel = new FlowLayoutPanel();
            root = new TableLayoutPanel();
            SuspendLayout();
            // 
            // txtName
            // 
            txtName.Dock = DockStyle.Fill;
            // 
            // txtPhone
            // 
            txtPhone.Dock = DockStyle.Fill;
            // 
            // txtEmail
            // 
            txtEmail.Dock = DockStyle.Fill;
            // 
            // txtAddress
            // 
            txtAddress.Dock = DockStyle.Fill;
            // 
            // chkActive
            // 
            chkActive.Text = "Active (uncheck to deactivate)";
            // 
            // lblName
            // 
            lblName.Anchor = AnchorStyles.Left;
            lblName.AutoSize = true;
            lblName.Text = "Name";
            // 
            // lblPhone
            // 
            lblPhone.Anchor = AnchorStyles.Left;
            lblPhone.AutoSize = true;
            lblPhone.Text = "Phone";
            // 
            // lblEmail
            // 
            lblEmail.Anchor = AnchorStyles.Left;
            lblEmail.AutoSize = true;
            lblEmail.Text = "Email";
            // 
            // lblAddress
            // 
            lblAddress.Anchor = AnchorStyles.Left;
            lblAddress.AutoSize = true;
            lblAddress.Text = "Address";
            // 
            // tblLayout
            // 
            tblLayout.ColumnCount = 1;
            tblLayout.RowCount = 9;
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 52));
            tblLayout.Controls.Add(lblName, 0, 0);
            tblLayout.Controls.Add(txtName, 0, 1);
            tblLayout.Controls.Add(lblPhone, 0, 2);
            tblLayout.Controls.Add(txtPhone, 0, 3);
            tblLayout.Controls.Add(lblEmail, 0, 4);
            tblLayout.Controls.Add(txtEmail, 0, 5);
            tblLayout.Controls.Add(lblAddress, 0, 6);
            tblLayout.Controls.Add(txtAddress, 0, 7);
            tblLayout.Controls.Add(chkActive, 0, 8);
            tblLayout.Dock = DockStyle.Fill;
            tblLayout.Padding = new Padding(16);
            // 
            // btnCancel
            // 
            btnCancel.BackColor = Color.FromArgb(149, 165, 166);
            btnCancel.Cursor = Cursors.Hand;
            btnCancel.FlatAppearance.BorderSize = 0;
            btnCancel.FlatStyle = FlatStyle.Flat;
            btnCancel.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnCancel.ForeColor = Color.White;
            btnCancel.Size = new Size(110, 36);
            btnCancel.Text = "Cancel";
            btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnSave
            // 
            btnSave.BackColor = Color.FromArgb(39, 174, 96);
            btnSave.Cursor = Cursors.Hand;
            btnSave.FlatAppearance.BorderSize = 0;
            btnSave.FlatStyle = FlatStyle.Flat;
            btnSave.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnSave.ForeColor = Color.White;
            btnSave.Size = new Size(110, 36);
            btnSave.Text = "Save";
            btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // btnPanel
            // 
            btnPanel.Controls.Add(btnCancel);
            btnPanel.Controls.Add(btnSave);
            btnPanel.Dock = DockStyle.Fill;
            btnPanel.FlowDirection = FlowDirection.RightToLeft;
            btnPanel.Padding = new Padding(0, 8, 0, 0);
            // 
            // root
            // 
            root.ColumnCount = 1;
            root.RowCount = 2;
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 52));
            root.Controls.Add(tblLayout, 0, 0);
            root.Controls.Add(btnPanel, 0, 1);
            root.Dock = DockStyle.Fill;
            root.Padding = new Padding(0);
            // 
            // FrmSupplierEdit
            // 
            AcceptButton = btnSave;
            CancelButton = btnCancel;
            ClientSize = new Size(460, 400);
            Controls.Add(root);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Shown += new System.EventHandler(this.FrmSupplierEdit_Shown);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.TextBox txtPhone;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.TextBox txtAddress;
        private System.Windows.Forms.CheckBox chkActive;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.Label lblPhone;
        private System.Windows.Forms.Label lblEmail;
        private System.Windows.Forms.Label lblAddress;
        private System.Windows.Forms.TableLayoutPanel tblLayout;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.FlowLayoutPanel btnPanel;
        private System.Windows.Forms.TableLayoutPanel root;
    }

    public partial class FrmCustomerList
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            dgv = new DataGridView();
            txtSearch = new TextBox();
            toolbar = new FlowLayoutPanel();
            lbl = new Label();
            btnNew = new Button();
            btnEdit = new Button();
            btnDelete = new Button();
            SuspendLayout();
            // 
            // dgv
            // 
            dgv.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_CellDoubleClick);
            dgv.Dock = DockStyle.Fill;
            // 
            // txtSearch
            // 
            txtSearch.Margin = new Padding(0, 6, 12, 0);
            txtSearch.Width = 220;
            txtSearch.TextChanged += new System.EventHandler(this.txtSearch_TextChanged);
            // 
            // lbl
            // 
            lbl.AutoSize = true;
            lbl.Margin = new Padding(0, 10, 4, 0);
            lbl.Text = "Search:";
            // 
            // btnNew
            // 
            btnNew.BackColor = Color.FromArgb(41, 128, 185);
            btnNew.Cursor = Cursors.Hand;
            btnNew.FlatAppearance.BorderSize = 0;
            btnNew.FlatStyle = FlatStyle.Flat;
            btnNew.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnNew.ForeColor = Color.White;
            btnNew.Margin = new Padding(0, 2, 8, 0);
            btnNew.Size = new Size(110, 36);
            btnNew.Text = "New (F2)";
            btnNew.Click += new System.EventHandler(this.btnNew_Click);
            // 
            // btnEdit
            // 
            btnEdit.BackColor = Color.FromArgb(39, 174, 96);
            btnEdit.Cursor = Cursors.Hand;
            btnEdit.FlatAppearance.BorderSize = 0;
            btnEdit.FlatStyle = FlatStyle.Flat;
            btnEdit.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnEdit.ForeColor = Color.White;
            btnEdit.Margin = new Padding(0, 2, 8, 0);
            btnEdit.Size = new Size(110, 36);
            btnEdit.Text = "Edit";
            btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            // 
            // btnDelete
            // 
            btnDelete.BackColor = Color.FromArgb(231, 76, 60);
            btnDelete.Cursor = Cursors.Hand;
            btnDelete.FlatAppearance.BorderSize = 0;
            btnDelete.FlatStyle = FlatStyle.Flat;
            btnDelete.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnDelete.ForeColor = Color.White;
            btnDelete.Margin = new Padding(0, 2, 8, 0);
            btnDelete.Size = new Size(110, 36);
            btnDelete.Text = "Delete";
            btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            // 
            // toolbar
            // 
            toolbar.Controls.Add(lbl);
            toolbar.Controls.Add(txtSearch);
            toolbar.Controls.Add(btnNew);
            toolbar.Controls.Add(btnEdit);
            toolbar.Controls.Add(btnDelete);
            toolbar.Dock = DockStyle.Top;
            toolbar.Height = 48;
            toolbar.Padding = new Padding(8, 8, 8, 0);
            toolbar.WrapContents = false;
            // 
            // FrmCustomerList
            // 
            ClientSize = new Size(800, 450);
            Controls.Add(dgv);
            Controls.Add(toolbar);
            KeyDown += new System.Windows.Forms.KeyEventHandler(this.FrmCustomerList_KeyDown);
            Load += new System.EventHandler(this.FrmCustomerList_Load);
            MinimumSize = new Size(550, 320);
            Text = "Customers";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.TextBox txtSearch;
        private System.Windows.Forms.FlowLayoutPanel toolbar;
        private System.Windows.Forms.Label lbl;
        private System.Windows.Forms.Button btnNew;
        private System.Windows.Forms.Button btnEdit;
        private System.Windows.Forms.Button btnDelete;
    }

    public partial class FrmCustomerEdit
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            txtName = new TextBox();
            txtPhone = new TextBox();
            txtEmail = new TextBox();
            txtAddress = new TextBox();
            lblName = new Label();
            lblPhone = new Label();
            lblEmail = new Label();
            lblAddress = new Label();
            tblLayout = new TableLayoutPanel();
            btnCancel = new Button();
            btnSave = new Button();
            btnPanel = new FlowLayoutPanel();
            root = new TableLayoutPanel();
            SuspendLayout();
            // 
            // txtName
            // 
            txtName.Dock = DockStyle.Fill;
            // 
            // txtPhone
            // 
            txtPhone.Dock = DockStyle.Fill;
            // 
            // txtEmail
            // 
            txtEmail.Dock = DockStyle.Fill;
            // 
            // txtAddress
            // 
            txtAddress.Height = 60;
            txtAddress.Dock = DockStyle.Fill;
            // 
            // lblName
            // 
            lblName.Anchor = AnchorStyles.Left;
            lblName.AutoSize = true;
            lblName.Text = "Name";
            // 
            // lblPhone
            // 
            lblPhone.Anchor = AnchorStyles.Left;
            lblPhone.AutoSize = true;
            lblPhone.Text = "Phone";
            // 
            // lblEmail
            // 
            lblEmail.Anchor = AnchorStyles.Left;
            lblEmail.AutoSize = true;
            lblEmail.Text = "Email";
            // 
            // lblAddress
            // 
            lblAddress.Anchor = AnchorStyles.Left;
            lblAddress.AutoSize = true;
            lblAddress.Text = "Address";
            // 
            // tblLayout
            // 
            tblLayout.ColumnCount = 1;
            tblLayout.RowCount = 8;
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            tblLayout.Controls.Add(lblName, 0, 0);
            tblLayout.Controls.Add(txtName, 0, 1);
            tblLayout.Controls.Add(lblPhone, 0, 2);
            tblLayout.Controls.Add(txtPhone, 0, 3);
            tblLayout.Controls.Add(lblEmail, 0, 4);
            tblLayout.Controls.Add(txtEmail, 0, 5);
            tblLayout.Controls.Add(lblAddress, 0, 6);
            tblLayout.Controls.Add(txtAddress, 0, 7);
            tblLayout.Dock = DockStyle.Fill;
            tblLayout.Padding = new Padding(16);
            // 
            // btnCancel
            // 
            btnCancel.BackColor = Color.FromArgb(149, 165, 166);
            btnCancel.Cursor = Cursors.Hand;
            btnCancel.FlatAppearance.BorderSize = 0;
            btnCancel.FlatStyle = FlatStyle.Flat;
            btnCancel.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnCancel.ForeColor = Color.White;
            btnCancel.Size = new Size(110, 36);
            btnCancel.Text = "Cancel";
            btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            // 
            // btnSave
            // 
            btnSave.BackColor = Color.FromArgb(39, 174, 96);
            btnSave.Cursor = Cursors.Hand;
            btnSave.FlatAppearance.BorderSize = 0;
            btnSave.FlatStyle = FlatStyle.Flat;
            btnSave.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnSave.ForeColor = Color.White;
            btnSave.Size = new Size(110, 36);
            btnSave.Text = "Save";
            btnSave.Click += new System.EventHandler(this.btnSave_Click);
            // 
            // btnPanel
            // 
            btnPanel.Controls.Add(btnCancel);
            btnPanel.Controls.Add(btnSave);
            btnPanel.Dock = DockStyle.Fill;
            btnPanel.FlowDirection = FlowDirection.RightToLeft;
            btnPanel.Padding = new Padding(0, 8, 0, 0);
            // 
            // root
            // 
            root.ColumnCount = 1;
            root.RowCount = 2;
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 52));
            root.Controls.Add(tblLayout, 0, 0);
            root.Controls.Add(btnPanel, 0, 1);
            root.Dock = DockStyle.Fill;
            // 
            // FrmCustomerEdit
            // 
            AcceptButton = btnSave;
            CancelButton = btnCancel;
            ClientSize = new Size(460, 360);
            Controls.Add(root);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Shown += new System.EventHandler(this.FrmCustomerEdit_Shown);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.TextBox txtPhone;
        private System.Windows.Forms.TextBox txtEmail;
        private System.Windows.Forms.TextBox txtAddress;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.Label lblPhone;
        private System.Windows.Forms.Label lblEmail;
        private System.Windows.Forms.Label lblAddress;
        private System.Windows.Forms.TableLayoutPanel tblLayout;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnSave;
        private System.Windows.Forms.FlowLayoutPanel btnPanel;
        private System.Windows.Forms.TableLayoutPanel root;
    }
}
