// <auto-generated>
//     This code was generated by a WinForms designer.
// </auto-generated>
#nullable disable

namespace pharmacy.Forms.Batches
{
    public partial class FrmBatchList
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            toolbar = new FlowLayoutPanel();
            chkHideDisposed = new CheckBox();
            btnRefresh = new Button();
            btnDispose = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            toolbar.Controls.AddRange(new Control[] { chkHideDisposed, btnRefresh, btnDispose });
            toolbar.Dock = DockStyle.Top;
            toolbar.Height = 48;
            toolbar.Padding = new Padding(8, 8, 8, 0);
            toolbar.WrapContents = false;
            chkHideDisposed.AutoSize = true;
            chkHideDisposed.Checked = true;
            chkHideDisposed.Margin = new Padding(0, 10, 16, 0);
            chkHideDisposed.Text = "Hide disposed";
            chkHideDisposed.CheckedChanged += new System.EventHandler(this.chkHideDisposed_CheckedChanged);
            btnRefresh.BackColor = Color.FromArgb(41, 128, 185);
            btnRefresh.Cursor = Cursors.Hand;
            btnRefresh.FlatAppearance.BorderSize = 0;
            btnRefresh.FlatStyle = FlatStyle.Flat;
            btnRefresh.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnRefresh.ForeColor = Color.White;
            btnRefresh.Height = 36;
            btnRefresh.Width = 110;
            btnRefresh.Margin = new Padding(0, 2, 8, 0);
            btnRefresh.Text = "Refresh";
            btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            btnDispose.BackColor = Color.FromArgb(231, 76, 60);
            btnDispose.Cursor = Cursors.Hand;
            btnDispose.FlatAppearance.BorderSize = 0;
            btnDispose.FlatStyle = FlatStyle.Flat;
            btnDispose.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnDispose.ForeColor = Color.White;
            btnDispose.Height = 36;
            btnDispose.Width = 110;
            btnDispose.Margin = new Padding(0, 2, 8, 0);
            btnDispose.Text = "Dispose";
            btnDispose.Click += new System.EventHandler(this.btnDispose_Click);
            dgv.CellFormatting += new System.Windows.Forms.DataGridViewCellFormattingEventHandler(this.dgv_CellFormatting);
            dgv.Dock = DockStyle.Fill;
            ClientSize = new Size(900, 480);
            Controls.AddRange(new Control[] { dgv, toolbar });
            Load += new System.EventHandler(this.FrmBatchList_Load);
            MinimumSize = new Size(600, 350);
            Text = "Batches";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel toolbar;
        private System.Windows.Forms.CheckBox chkHideDisposed;
        private System.Windows.Forms.Button btnRefresh;
        private System.Windows.Forms.Button btnDispose;
        private System.Windows.Forms.DataGridView dgv;
    }

    public partial class FrmExpiryAlerts
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            toolbar = new FlowLayoutPanel();
            lblSummary = new Label();
            btnRefresh = new Button();
            btnDispose = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            toolbar.Controls.AddRange(new Control[] { lblSummary, btnRefresh, btnDispose });
            toolbar.Dock = DockStyle.Top;
            toolbar.Height = 48;
            toolbar.Padding = new Padding(8, 8, 8, 0);
            toolbar.WrapContents = false;
            lblSummary.AutoSize = true;
            lblSummary.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblSummary.ForeColor = Color.FromArgb(192, 57, 43);
            lblSummary.Margin = new Padding(0, 12, 24, 0);
            btnRefresh.BackColor = Color.FromArgb(41, 128, 185);
            btnRefresh.Cursor = Cursors.Hand;
            btnRefresh.FlatAppearance.BorderSize = 0;
            btnRefresh.FlatStyle = FlatStyle.Flat;
            btnRefresh.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnRefresh.ForeColor = Color.White;
            btnRefresh.Height = 36;
            btnRefresh.Width = 110;
            btnRefresh.Margin = new Padding(0, 2, 8, 0);
            btnRefresh.Text = "Refresh";
            btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            btnDispose.BackColor = Color.FromArgb(231, 76, 60);
            btnDispose.Cursor = Cursors.Hand;
            btnDispose.FlatAppearance.BorderSize = 0;
            btnDispose.FlatStyle = FlatStyle.Flat;
            btnDispose.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnDispose.ForeColor = Color.White;
            btnDispose.Height = 36;
            btnDispose.Width = 110;
            btnDispose.Margin = new Padding(0, 2, 8, 0);
            btnDispose.Text = "Dispose";
            btnDispose.Click += new System.EventHandler(this.btnDispose_Click);
            dgv.CellFormatting += new System.Windows.Forms.DataGridViewCellFormattingEventHandler(this.dgv_CellFormatting);
            dgv.Dock = DockStyle.Fill;
            ClientSize = new Size(950, 500);
            Controls.AddRange(new Control[] { dgv, toolbar });
            Load += new System.EventHandler(this.FrmExpiryAlerts_Load);
            MinimumSize = new Size(600, 350);
            Text = "Expiry Alerts (30 / 60 / 90 / Expired)";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel toolbar;
        private System.Windows.Forms.Label lblSummary;
        private System.Windows.Forms.Button btnRefresh;
        private System.Windows.Forms.Button btnDispose;
        private System.Windows.Forms.DataGridView dgv;
    }
}
