// <auto-generated>
//     This code was generated by a WinForms designer.
// </auto-generated>
#nullable disable

namespace pharmacy.Forms.Categories
{
    public partial class FrmCategoryList
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            toolbar = new FlowLayoutPanel();
            lbl = new Label();
            txtSearch = new TextBox();
            btnNew = new Button();
            btnEdit = new Button();
            btnDelete = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            toolbar.Controls.AddRange(new Control[] { lbl, txtSearch, btnNew, btnEdit, btnDelete });
            toolbar.Dock = DockStyle.Top;
            toolbar.Height = 48;
            toolbar.Padding = new Padding(8, 8, 8, 0);
            toolbar.WrapContents = false;
            lbl.AutoSize = true;
            lbl.Margin = new Padding(0, 10, 4, 0);
            lbl.Text = "Search:";
            txtSearch.Margin = new Padding(0, 6, 12, 0);
            txtSearch.Width = 220;
            txtSearch.TextChanged += new System.EventHandler(this.txtSearch_TextChanged);
            btnNew.BackColor = Color.FromArgb(41, 128, 185);
            btnNew.Cursor = Cursors.Hand;
            btnNew.FlatAppearance.BorderSize = 0;
            btnNew.FlatStyle = FlatStyle.Flat;
            btnNew.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnNew.ForeColor = Color.White;
            btnNew.Height = 36;
            btnNew.Width = 110;
            btnNew.Margin = new Padding(0, 2, 8, 0);
            btnNew.Text = "New (F2)";
            btnNew.Click += new System.EventHandler(this.btnNew_Click);
            btnEdit.BackColor = Color.FromArgb(39, 174, 96);
            btnEdit.Cursor = Cursors.Hand;
            btnEdit.FlatAppearance.BorderSize = 0;
            btnEdit.FlatStyle = FlatStyle.Flat;
            btnEdit.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnEdit.ForeColor = Color.White;
            btnEdit.Height = 36;
            btnEdit.Width = 110;
            btnEdit.Margin = new Padding(0, 2, 8, 0);
            btnEdit.Text = "Edit";
            btnEdit.Click += new System.EventHandler(this.btnEdit_Click);
            btnDelete.BackColor = Color.FromArgb(231, 76, 60);
            btnDelete.Cursor = Cursors.Hand;
            btnDelete.FlatAppearance.BorderSize = 0;
            btnDelete.FlatStyle = FlatStyle.Flat;
            btnDelete.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnDelete.ForeColor = Color.White;
            btnDelete.Height = 36;
            btnDelete.Width = 110;
            btnDelete.Margin = new Padding(0, 2, 8, 0);
            btnDelete.Text = "Delete";
            btnDelete.Click += new System.EventHandler(this.btnDelete_Click);
            dgv.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_CellDoubleClick);
            dgv.Dock = DockStyle.Fill;
            ClientSize = new Size(700, 450);
            Controls.AddRange(new Control[] { dgv, toolbar });
            KeyDown += new System.Windows.Forms.KeyEventHandler(this.FrmCategoryList_KeyDown);
            Load += new System.EventHandler(this.FrmCategoryList_Load);
            MinimumSize = new Size(500, 300);
            Text = "Categories";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel toolbar;
        private System.Windows.Forms.Label lbl;
        private System.Windows.Forms.TextBox txtSearch;
        private System.Windows.Forms.Button btnNew;
        private System.Windows.Forms.Button btnEdit;
        private System.Windows.Forms.Button btnDelete;
        private System.Windows.Forms.DataGridView dgv;
    }

    public partial class FrmCategoryEdit
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            layout = new TableLayoutPanel();
            lblName = new Label();
            txtName = new TextBox();
            lblDesc = new Label();
            txtDesc = new TextBox();
            btnPanel = new FlowLayoutPanel();
            btnCancel = new Button();
            btnSave = new Button();
            SuspendLayout();
            layout.Dock = DockStyle.Fill;
            layout.Padding = new Padding(16);
            layout.ColumnCount = 1;
            layout.RowCount = 5;
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 24));
            layout.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            layout.RowStyles.Add(new RowStyle(SizeType.Absolute, 48));
            lblName.Anchor = AnchorStyles.Left;
            lblName.AutoSize = true;
            lblName.Text = "Name";
            layout.Controls.Add(lblName, 0, 0);
            txtName.Dock = DockStyle.Fill;
            layout.Controls.Add(txtName, 0, 1);
            lblDesc.Anchor = AnchorStyles.Left;
            lblDesc.AutoSize = true;
            lblDesc.Text = "Description";
            layout.Controls.Add(lblDesc, 0, 2);
            txtDesc.Dock = DockStyle.Fill;
            txtDesc.Multiline = true;
            txtDesc.ScrollBars = ScrollBars.Vertical;
            layout.Controls.Add(txtDesc, 0, 3);
            btnCancel.BackColor = Color.FromArgb(149, 165, 166);
            btnCancel.Cursor = Cursors.Hand;
            btnCancel.FlatAppearance.BorderSize = 0;
            btnCancel.FlatStyle = FlatStyle.Flat;
            btnCancel.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnCancel.ForeColor = Color.White;
            btnCancel.Height = 36;
            btnCancel.Width = 110;
            btnCancel.Text = "Cancel";
            btnCancel.Click += new System.EventHandler(this.btnCancel_Click);
            btnSave.BackColor = Color.FromArgb(39, 174, 96);
            btnSave.Cursor = Cursors.Hand;
            btnSave.FlatAppearance.BorderSize = 0;
            btnSave.FlatStyle = FlatStyle.Flat;
            btnSave.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnSave.ForeColor = Color.White;
            btnSave.Height = 36;
            btnSave.Width = 110;
            btnSave.Text = "Save";
            btnSave.Click += new System.EventHandler(this.btnSave_Click);
            btnPanel.Controls.Add(btnCancel);
            btnPanel.Controls.Add(btnSave);
            btnPanel.Dock = DockStyle.Fill;
            btnPanel.FlowDirection = FlowDirection.RightToLeft;
            btnPanel.Padding = new Padding(0, 8, 0, 0);
            layout.Controls.Add(btnPanel, 0, 4);
            AcceptButton = btnSave;
            CancelButton = btnCancel;
            ClientSize = new Size(440, 280);
            Controls.Add(layout);
            FormBorderStyle = FormBorderStyle.FixedDialog;
            MaximizeBox = false;
            MinimizeBox = false;
            Shown += new System.EventHandler(this.FrmCategoryEdit_Shown);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel layout;
        private System.Windows.Forms.Label lblName;
        private System.Windows.Forms.TextBox txtName;
        private System.Windows.Forms.Label lblDesc;
        private System.Windows.Forms.TextBox txtDesc;
        private System.Windows.Forms.FlowLayoutPanel btnPanel;
        private System.Windows.Forms.Button btnCancel;
        private System.Windows.Forms.Button btnSave;
    }
}
