// <auto-generated>
//     This code was generated by a WinForms designer.
// </auto-generated>
#nullable disable

namespace pharmacy.Forms.Sales
{
    public partial class FrmPos
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            topBar = new Panel();
            lblSearch = new Label();
            txtSearch = new TextBox();
            split = new TableLayoutPanel();
            left = new TableLayoutPanel();
            dgvSearch = new DataGridView();
            addPanel = new FlowLayoutPanel();
            lblQty = new Label();
            numQty = new NumericUpDown();
            btnAdd = new Button();
            bottomLeft = new TableLayoutPanel();
            cmbPayment = new ComboBox();
            cmbCustomer = new ComboBox();
            numDiscount = new NumericUpDown();
            numPaid = new NumericUpDown();
            lblTotal = new Label();
            right = new TableLayoutPanel();
            dgvCart = new DataGridView();
            cartBtns = new FlowLayoutPanel();
            btnRemove = new Button();
            btnClear = new Button();
            checkoutPanel = new FlowLayoutPanel();
            btnCheckout = new Button();
            SuspendLayout();
            // 
            // topBar
            // 
            topBar.Dock = DockStyle.Top;
            topBar.Height = 48;
            topBar.Padding = new Padding(8, 12, 8, 0);
            // 
            // lblSearch
            // 
            lblSearch.AutoSize = true;
            lblSearch.Location = new Point(8, 14);
            lblSearch.Text = "Scan / search (F4):";
            // 
            // txtSearch
            // 
            txtSearch.Location = new Point(150, 10);
            txtSearch.Width = 360;
            txtSearch.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            txtSearch.TextChanged += new System.EventHandler(this.txtSearch_TextChanged);
            txtSearch.KeyDown += new System.Windows.Forms.KeyEventHandler(this.txtSearch_KeyDown);
            topBar.Controls.AddRange(new Control[] { lblSearch, txtSearch });
            // 
            // split
            // 
            split.Dock = DockStyle.Fill;
            split.ColumnCount = 2;
            split.RowCount = 1;
            split.Padding = new Padding(4);
            split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
            split.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50));
            // 
            // left
            // 
            left.Dock = DockStyle.Fill;
            left.RowCount = 3;
            left.ColumnCount = 1;
            left.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            left.RowStyles.Add(new RowStyle(SizeType.Absolute, 44));
            left.RowStyles.Add(new RowStyle(SizeType.Absolute, 140));
            // 
            // dgvSearch
            // 
            dgvSearch.Dock = DockStyle.Fill;
            dgvSearch.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvSearch_CellDoubleClick);
            dgvSearch.KeyDown += new System.Windows.Forms.KeyEventHandler(this.dgvSearch_KeyDown);
            // 
            // addPanel
            // 
            addPanel.Dock = DockStyle.Fill;
            addPanel.Padding = new Padding(0, 6, 0, 0);
            // 
            // lblQty
            // 
            lblQty.AutoSize = true;
            lblQty.Margin = new Padding(0, 8, 4, 0);
            lblQty.Text = "Qty:";
            // 
            // numQty
            // 
            numQty.Minimum = 1;
            numQty.Maximum = 9999;
            numQty.Value = 1;
            numQty.Width = 70;
            // 
            // btnAdd
            // 
            btnAdd.BackColor = Color.FromArgb(41, 128, 185);
            btnAdd.Cursor = Cursors.Hand;
            btnAdd.FlatAppearance.BorderSize = 0;
            btnAdd.FlatStyle = FlatStyle.Flat;
            btnAdd.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnAdd.ForeColor = Color.White;
            btnAdd.Height = 36;
            btnAdd.Width = 110;
            btnAdd.Margin = new Padding(8, 2, 0, 0);
            btnAdd.Text = "Add (Enter)";
            btnAdd.Click += new System.EventHandler(this.btnAdd_Click);
            addPanel.Controls.AddRange(new Control[] { lblQty, numQty, btnAdd });
            // 
            // bottomLeft
            // 
            bottomLeft.Dock = DockStyle.Fill;
            bottomLeft.RowCount = 4;
            bottomLeft.ColumnCount = 4;
            bottomLeft.Padding = new Padding(0, 4, 8, 0);
            bottomLeft.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
            bottomLeft.RowStyles.Add(new RowStyle(SizeType.Absolute, 32));
            bottomLeft.RowStyles.Add(new RowStyle(SizeType.Absolute, 36));
            bottomLeft.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            bottomLeft.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 80));
            bottomLeft.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 120));
            bottomLeft.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 90));
            bottomLeft.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100));
            // 
            // cmbPayment
            // 
            cmbPayment.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbPayment.Width = 120;
            // 
            // cmbCustomer
            // 
            cmbCustomer.DropDownStyle = ComboBoxStyle.DropDownList;
            cmbCustomer.Width = 160;
            // 
            // numDiscount
            // 
            numDiscount.Maximum = 100000;
            numDiscount.DecimalPlaces = 2;
            numDiscount.Width = 100;
            numDiscount.ValueChanged += new System.EventHandler(this.numDiscount_ValueChanged);
            // 
            // numPaid
            // 
            numPaid.Maximum = 100000;
            numPaid.DecimalPlaces = 2;
            numPaid.Width = 100;
            bottomLeft.Controls.Add(new Label { Text = "Payment:", AutoSize = true, Anchor = AnchorStyles.Left }, 0, 0);
            bottomLeft.Controls.Add(cmbPayment, 1, 0);
            bottomLeft.Controls.Add(new Label { Text = "Customer:", AutoSize = true, Anchor = AnchorStyles.Left }, 0, 1);
            bottomLeft.Controls.Add(cmbCustomer, 1, 1);
            bottomLeft.Controls.Add(new Label { Text = "Discount:", AutoSize = true, Anchor = AnchorStyles.Left }, 0, 2);
            bottomLeft.Controls.Add(numDiscount, 1, 2);
            bottomLeft.Controls.Add(new Label { Text = "Paid:", AutoSize = true, Anchor = AnchorStyles.Left }, 2, 2);
            bottomLeft.Controls.Add(numPaid, 3, 2);
            // 
            // lblTotal
            // 
            lblTotal.Text = "Total: 0.00";
            lblTotal.Font = new Font("Segoe UI", 18F, FontStyle.Bold);
            lblTotal.ForeColor = Color.FromArgb(39, 174, 96);
            lblTotal.Dock = DockStyle.Fill;
            lblTotal.TextAlign = ContentAlignment.MiddleRight;
            bottomLeft.Controls.Add(lblTotal, 0, 3);
            bottomLeft.SetColumnSpan(lblTotal, 4);
            left.Controls.Add(dgvSearch, 0, 0);
            left.Controls.Add(addPanel, 0, 1);
            left.Controls.Add(bottomLeft, 0, 2);
            // 
            // right
            // 
            right.Dock = DockStyle.Fill;
            right.RowCount = 3;
            right.ColumnCount = 1;
            right.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            right.RowStyles.Add(new RowStyle(SizeType.Absolute, 44));
            right.RowStyles.Add(new RowStyle(SizeType.Absolute, 56));
            // 
            // dgvCart
            // 
            dgvCart.Dock = DockStyle.Fill;
            // 
            // cartBtns
            // 
            cartBtns.Dock = DockStyle.Fill;
            cartBtns.Padding = new Padding(0, 6, 0, 0);
            // 
            // btnRemove
            // 
            btnRemove.BackColor = Color.FromArgb(231, 76, 60);
            btnRemove.Cursor = Cursors.Hand;
            btnRemove.FlatAppearance.BorderSize = 0;
            btnRemove.FlatStyle = FlatStyle.Flat;
            btnRemove.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnRemove.ForeColor = Color.White;
            btnRemove.Height = 36;
            btnRemove.Width = 110;
            btnRemove.Margin = new Padding(0, 2, 8, 0);
            btnRemove.Text = "Remove Line";
            btnRemove.Click += new System.EventHandler(this.btnRemove_Click);
            // 
            // btnClear
            // 
            btnClear.BackColor = Color.FromArgb(149, 165, 166);
            btnClear.Cursor = Cursors.Hand;
            btnClear.FlatAppearance.BorderSize = 0;
            btnClear.FlatStyle = FlatStyle.Flat;
            btnClear.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnClear.ForeColor = Color.White;
            btnClear.Height = 36;
            btnClear.Width = 110;
            btnClear.Margin = new Padding(0, 2, 0, 0);
            btnClear.Text = "Clear Cart";
            btnClear.Click += new System.EventHandler(this.btnClear_Click);
            cartBtns.Controls.AddRange(new Control[] { btnRemove, btnClear });
            // 
            // checkoutPanel
            // 
            checkoutPanel.Dock = DockStyle.Fill;
            checkoutPanel.FlowDirection = FlowDirection.RightToLeft;
            checkoutPanel.Padding = new Padding(0, 4, 0, 0);
            // 
            // btnCheckout
            // 
            btnCheckout.BackColor = Color.FromArgb(39, 174, 96);
            btnCheckout.Cursor = Cursors.Hand;
            btnCheckout.FlatAppearance.BorderSize = 0;
            btnCheckout.FlatStyle = FlatStyle.Flat;
            btnCheckout.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnCheckout.ForeColor = Color.White;
            btnCheckout.Height = 36;
            btnCheckout.Width = 110;
            btnCheckout.Size = new Size(220, 48);
            btnCheckout.Text = "Checkout (F8)";
            btnCheckout.Click += new System.EventHandler(this.btnCheckout_Click);
            checkoutPanel.Controls.Add(btnCheckout);
            right.Controls.Add(dgvCart, 0, 0);
            right.Controls.Add(cartBtns, 0, 1);
            right.Controls.Add(checkoutPanel, 0, 2);
            split.Controls.Add(left, 0, 0);
            split.Controls.Add(right, 1, 0);
            // 
            // FrmPos
            // 
            ClientSize = new Size(1100, 680);
            Controls.Add(split);
            Controls.Add(topBar);
            KeyDown += new System.Windows.Forms.KeyEventHandler(this.FrmPos_KeyDown);
            MinimumSize = new Size(900, 560);
            Shown += new System.EventHandler(this.FrmPos_Shown);
            Text = "Point of Sale";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Panel topBar;
        private System.Windows.Forms.Label lblSearch;
        private System.Windows.Forms.TextBox txtSearch;
        private System.Windows.Forms.TableLayoutPanel split;
        private System.Windows.Forms.TableLayoutPanel left;
        private System.Windows.Forms.DataGridView dgvSearch;
        private System.Windows.Forms.FlowLayoutPanel addPanel;
        private System.Windows.Forms.Label lblQty;
        private System.Windows.Forms.NumericUpDown numQty;
        private System.Windows.Forms.Button btnAdd;
        private System.Windows.Forms.TableLayoutPanel bottomLeft;
        private System.Windows.Forms.ComboBox cmbPayment;
        private System.Windows.Forms.ComboBox cmbCustomer;
        private System.Windows.Forms.NumericUpDown numDiscount;
        private System.Windows.Forms.NumericUpDown numPaid;
        private System.Windows.Forms.Label lblTotal;
        private System.Windows.Forms.TableLayoutPanel right;
        private System.Windows.Forms.DataGridView dgvCart;
        private System.Windows.Forms.FlowLayoutPanel cartBtns;
        private System.Windows.Forms.Button btnRemove;
        private System.Windows.Forms.Button btnClear;
        private System.Windows.Forms.FlowLayoutPanel checkoutPanel;
        private System.Windows.Forms.Button btnCheckout;
    }

    public partial class FrmSaleList
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            toolbar = new FlowLayoutPanel();
            btnRefresh = new Button();
            btnView = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            // 
            // toolbar
            // 
            toolbar.Dock = DockStyle.Top;
            toolbar.Height = 48;
            toolbar.Padding = new Padding(8, 8, 8, 0);
            toolbar.WrapContents = false;
            // 
            // btnRefresh
            // 
            btnRefresh.BackColor = Color.FromArgb(41, 128, 185);
            btnRefresh.Cursor = Cursors.Hand;
            btnRefresh.FlatAppearance.BorderSize = 0;
            btnRefresh.FlatStyle = FlatStyle.Flat;
            btnRefresh.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnRefresh.ForeColor = Color.White;
            btnRefresh.Height = 36;
            btnRefresh.Width = 110;
            btnRefresh.Margin = new Padding(0, 2, 8, 0);
            btnRefresh.Text = "Refresh";
            btnRefresh.Click += new System.EventHandler(this.btnRefresh_Click);
            // 
            // btnView
            // 
            btnView.BackColor = Color.FromArgb(39, 174, 96);
            btnView.Cursor = Cursors.Hand;
            btnView.FlatAppearance.BorderSize = 0;
            btnView.FlatStyle = FlatStyle.Flat;
            btnView.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnView.ForeColor = Color.White;
            btnView.Height = 36;
            btnView.Width = 110;
            btnView.Margin = new Padding(0, 2, 8, 0);
            btnView.Text = "View";
            btnView.Click += new System.EventHandler(this.btnView_Click);
            toolbar.Controls.AddRange(new Control[] { btnRefresh, btnView });
            // 
            // dgv
            // 
            dgv.Dock = DockStyle.Fill;
            dgv.CellDoubleClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgv_CellDoubleClick);
            // 
            // FrmSaleList
            // 
            ClientSize = new Size(900, 480);
            Controls.AddRange(new Control[] { dgv, toolbar });
            Load += new System.EventHandler(this.FrmSaleList_Load);
            MinimumSize = new Size(600, 350);
            Text = "Sales";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.FlowLayoutPanel toolbar;
        private System.Windows.Forms.Button btnRefresh;
        private System.Windows.Forms.Button btnView;
        private System.Windows.Forms.DataGridView dgv;
    }

    public partial class FrmSaleView
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            root = new TableLayoutPanel();
            info = new Label();
            dgv = new DataGridView();
            btnPanel = new FlowLayoutPanel();
            btnClose = new Button();
            SuspendLayout();
            // 
            // root
            // 
            root.Dock = DockStyle.Fill;
            root.RowCount = 3;
            root.ColumnCount = 1;
            root.Padding = new Padding(12);
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 90));
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 52));
            // 
            // info
            // 
            info.Dock = DockStyle.Fill;
            // 
            // dgv
            // 
            dgv.Dock = DockStyle.Fill;
            // 
            // btnPanel
            // 
            btnPanel.Dock = DockStyle.Fill;
            btnPanel.FlowDirection = FlowDirection.RightToLeft;
            // 
            // btnClose
            // 
            btnClose.BackColor = Color.FromArgb(149, 165, 166);
            btnClose.Cursor = Cursors.Hand;
            btnClose.FlatAppearance.BorderSize = 0;
            btnClose.FlatStyle = FlatStyle.Flat;
            btnClose.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnClose.ForeColor = Color.White;
            btnClose.Height = 36;
            btnClose.Width = 110;
            btnClose.Text = "Close";
            btnClose.Click += new System.EventHandler(this.btnClose_Click);
            btnPanel.Controls.Add(btnClose);
            root.Controls.Add(info, 0, 0);
            root.Controls.Add(dgv, 0, 1);
            root.Controls.Add(btnPanel, 0, 2);
            // 
            // FrmSaleView
            // 
            AcceptButton = btnClose;
            ClientSize = new Size(700, 460);
            Controls.Add(root);
            MinimumSize = new Size(500, 350);
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel root;
        private System.Windows.Forms.Label info;
        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.FlowLayoutPanel btnPanel;
        private System.Windows.Forms.Button btnClose;
    }
}
