// <auto-generated>
//     This code was generated by a WinForms designer.
// </auto-generated>
#nullable disable

namespace pharmacy.Forms.Reports
{
    public partial class FrmSalesReport
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            dtFrom = new DateTimePicker();
            dtTo = new DateTimePicker();
            dgv = new DataGridView();
            lblTotal = new Label();
            bar = new FlowLayoutPanel();
            lblFrom = new Label();
            lblTo = new Label();
            SuspendLayout();
            bar.Dock = DockStyle.Top;
            bar.Height = 48;
            bar.Padding = new Padding(8, 12, 8, 0);
            bar.WrapContents = false;
            lblFrom.AutoSize = true;
            lblFrom.Margin = new Padding(0, 6, 4, 0);
            lblFrom.Text = "From:";
            dtFrom.Format = DateTimePickerFormat.Short;
            dtFrom.Margin = new Padding(0, 4, 12, 0);
            dtFrom.Width = 120;
            lblTo.AutoSize = true;
            lblTo.Margin = new Padding(0, 6, 4, 0);
            lblTo.Text = "To:";
            dtTo.Format = DateTimePickerFormat.Short;
            dtTo.Margin = new Padding(0, 4, 16, 0);
            dtTo.Width = 120;
            lblTotal.AutoSize = true;
            lblTotal.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblTotal.Margin = new Padding(0, 4, 0, 0);
            bar.Controls.AddRange(new Control[] { lblFrom, dtFrom, lblTo, dtTo, lblTotal });
            dgv.CellDoubleClick += dgv_CellDoubleClick;
            dgv.Dock = DockStyle.Fill;
            ClientSize = new Size(900, 500);
            Controls.Add(dgv);
            Controls.Add(bar);
            Load += FrmSalesReport_Load;
            Text = "Sales Report";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.DateTimePicker dtFrom;
        private System.Windows.Forms.DateTimePicker dtTo;
        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.Label lblTotal;
        private System.Windows.Forms.FlowLayoutPanel bar;
        private System.Windows.Forms.Label lblFrom;
        private System.Windows.Forms.Label lblTo;
    }

    public partial class FrmStockReport
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            btnRun = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            btnRun.BackColor = Color.FromArgb(41, 128, 185);
            btnRun.Cursor = Cursors.Hand;
            btnRun.FlatAppearance.BorderSize = 0;
            btnRun.FlatStyle = FlatStyle.Flat;
            btnRun.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnRun.ForeColor = Color.White;
            btnRun.Height = 36;
            btnRun.Width = 110;
            btnRun.Location = new Point(12, 12);
            btnRun.Text = "Refresh";
            btnRun.Click += btnRun_Click;
            dgv.CellDoubleClick += dgv_CellDoubleClick;
            dgv.CellFormatting += dgv_CellFormatting;
            dgv.Location = new Point(12, 55);
            dgv.Size = new Size(870, 430);
            ClientSize = new Size(900, 500);
            Controls.Add(btnRun);
            Controls.Add(dgv);
            Load += FrmStockReport_Load;
            Text = "Stock Report";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Button btnRun;
        private System.Windows.Forms.DataGridView dgv;
    }

    public partial class FrmProfitReport
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            dtFrom = new DateTimePicker();
            dtTo = new DateTimePicker();
            dgv = new DataGridView();
            lblTotal = new Label();
            bar = new FlowLayoutPanel();
            lblFrom = new Label();
            lblTo = new Label();
            SuspendLayout();
            bar.Dock = DockStyle.Top;
            bar.Height = 48;
            bar.Padding = new Padding(8, 12, 8, 0);
            bar.WrapContents = false;
            lblFrom.AutoSize = true;
            lblFrom.Margin = new Padding(0, 6, 4, 0);
            lblFrom.Text = "From:";
            dtFrom.Format = DateTimePickerFormat.Short;
            dtFrom.Margin = new Padding(0, 4, 12, 0);
            dtFrom.Width = 120;
            lblTo.AutoSize = true;
            lblTo.Margin = new Padding(0, 6, 4, 0);
            lblTo.Text = "To:";
            dtTo.Format = DateTimePickerFormat.Short;
            dtTo.Margin = new Padding(0, 4, 16, 0);
            dtTo.Width = 120;
            lblTotal.AutoSize = true;
            lblTotal.Font = new Font("Segoe UI", 11F, FontStyle.Bold);
            lblTotal.ForeColor = Color.FromArgb(39, 174, 96);
            lblTotal.Margin = new Padding(0, 4, 0, 0);
            bar.Controls.AddRange(new Control[] { lblFrom, dtFrom, lblTo, dtTo, lblTotal });
            dgv.Dock = DockStyle.Fill;
            ClientSize = new Size(900, 500);
            Controls.Add(dgv);
            Controls.Add(bar);
            Load += FrmProfitReport_Load;
            Text = "Profit Report (Revenue − Cost)";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.DateTimePicker dtFrom;
        private System.Windows.Forms.DateTimePicker dtTo;
        private System.Windows.Forms.DataGridView dgv;
        private System.Windows.Forms.Label lblTotal;
        private System.Windows.Forms.FlowLayoutPanel bar;
        private System.Windows.Forms.Label lblFrom;
        private System.Windows.Forms.Label lblTo;
    }

    public partial class FrmExpiryReport
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            btnRun = new Button();
            dgv = new DataGridView();
            SuspendLayout();
            btnRun.BackColor = Color.FromArgb(41, 128, 185);
            btnRun.Cursor = Cursors.Hand;
            btnRun.FlatAppearance.BorderSize = 0;
            btnRun.FlatStyle = FlatStyle.Flat;
            btnRun.Font = new Font("Segoe UI", 9.75F, FontStyle.Bold);
            btnRun.ForeColor = Color.White;
            btnRun.Height = 36;
            btnRun.Width = 110;
            btnRun.Location = new Point(12, 12);
            btnRun.Text = "Refresh";
            btnRun.Click += btnRun_Click;
            dgv.CellDoubleClick += dgv_CellDoubleClick;
            dgv.Location = new Point(12, 55);
            dgv.Size = new Size(870, 430);
            ClientSize = new Size(900, 500);
            Controls.Add(btnRun);
            Controls.Add(dgv);
            Load += FrmExpiryReport_Load;
            Text = "Expiry Report";
            ResumeLayout(false);
            PerformLayout();
        }

        #endregion

        private System.Windows.Forms.Button btnRun;
        private System.Windows.Forms.DataGridView dgv;
    }
}
